# Generated by Django 5.2 on 2025-05-04 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_prompt",
                    models.TextField(blank=True, verbose_name="초기 프롬프트"),
                ),
                ("selected_prompt", models.TextField(verbose_name="선택된 프롬프트(응답)")),
                (
                    "model_outputs",
                    models.JSONField(default=list, verbose_name="전체 모델 응답"),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=100, verbose_name="선택 이유"),
                ),
                (
                    "saved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="저장 시각"),
                ),
                (
                    "chat_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main_app.chatsession",
                        verbose_name="채팅 세션",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "저장된 프롬프트",
                "verbose_name_plural": "저장된 프롬프트 목록",
                "ordering": ["-saved_at"],
            },
        ),
    ]
