# Generated by Django 5.2 on 2025-05-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_savedprompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(unique=True, verbose_name="데모 질문")),
                ("answer", models.TextField(verbose_name="데모 답변")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="카테고리 (선택)"
                    ),
                ),
            ],
            options={
                "verbose_name": "데모 질문/답변",
                "verbose_name_plural": "데모 질문/답변 목록",
                "ordering": ["id"],
            },
        ),
    ]
